steps:
  # 0. Construir la imagen
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Construir-Imagen'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/user-manager-api:$COMMIT_SHA'
      - '.'

  # 1. EJECUTAR PRUEBAS 
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Ejecutar-Pytest'
    args:
      - 'run'
      - '-e'
      - 'DATABASE_URL=sqlite+aiosqlite:///:memory:'
      - 'gcr.io/$PROJECT_ID/user-manager-api:$COMMIT_SHA'
      - 'python'
      - '-m'
      - 'pytest'
      - '-v'

  # 2. Subir la imagen al registro
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Subir-Imagen'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/user-manager-api:$COMMIT_SHA'

  # 3. Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Desplegar-Cloud-Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--memory=512Mi'
      - 'stefanini-users-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/user-manager-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL}'

images:
  - 'gcr.io/$PROJECT_ID/user-manager-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY